# Generated by Django 5.2.1 on 2025-05-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfildeusuario_especialidad_perfildeusuario_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildeusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
    ]
